# parse: Options affecting listfile parsing
parse:
  additional_commands:
    calamares_add_branding:
      pargs:
        nargs: 1+
        flags: []
      kwargs:
        DIRECTORY: 1
        SUBDIRECTORIES: +
    calamares_add_branding_translations:
      pargs:
        nargs: 1+
        flags: []
      kwargs:
        DIRECTORY: 1
    calamares_add_branding_subdirectory:
      pargs:
        nargs: 1+
        flags: []
      kwargs:
        NAME: 1
        SUBDIRECTORIES: +
    calamares_add_library:
      pargs:
        nargs: '*'
        flags:
        - NO_INSTALL
        - NO_VERSION
      kwargs:
        NAME: 1
        EXPORT_MACRO: 1
        TARGET_TYPE: 1
        EXPORT: 1
        VERSION: 1
        SOVERSION: 1
        INSTALL_BINDIR: 1
        RESOURCES: 1
        SOURCES: +
        UI: +
        LINK_LIBRARIES: +
        LINK_PRIVATE_LIBRARIES: +
        COMPILE_DEFINITIONS: +
    calamares_add_module_subdirectory:
      pargs:
        nargs: 0
    calamares_add_plugin:
      pargs:
        nargs: '*'
        flags:
        - NO_CONFIG
        - NO_INSTALL
        - SHARED_LIB
        - EMERGENCY
      kwargs:
        NAME: 1
        TYPE: 1
        EXPORT_MACRO: 1
        RESOURCES: 1
        WEIGHT: 1
        SOURCES: +
        UI: +
        LINK_LIBRARIES: +
        LINK_PRIVATE_LIBRARIES: +
        COMPILE_DEFINITIONS: +
        REQUIRES: +
    calamares_add_test:
      pargs:
        nargs: '*'
        flags:
        - GUI
      kwargs:
        NAME: 1
        RESOURCES: 1
        SOURCES: +
        LIBRARIES: +
        DEFINITIONS: +
    install_calamares_gettext_translations:
      pargs:
        nargs: '*'
        flags: []
      kwargs:
        NAME: 1
        SOURCE_DIR: 1
        FILENAME: 1
        RENAME: 1
    calamares_automoc:
      pargs:
        nargs: 1
    calamares_autouic:
      pargs:
        nargs: 1
    calamares_autorcc:
      pargs:
        nargs: 1
    calamares_skip_module:
      pargs:
        nargs: 0
    calamares_explain_skipped_modules:
      pargs:
        nargs: 0
    calamares_check_skip:
      pargs:
        nargs: 2

# format: Options affecting formatting.
format:
  disable: false
  line_width: 120
  tab_size: 4
  use_tabchars: false

  dangle_parens: true
  dangle_align: prefix

  min_prefix_chars: 8
  max_prefix_chars: 0
  max_lines_hwrap: 2

  command_case: lower
  keyword_case: upper
  enable_sort: true
  autosort: false

markup:
  enable_markup: false

